workflows:
  android-release-apk:
    name: Android Release APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    working_directory: mobile
    environment:
      vars:
        CI: 1
        EXPO_NO_TELEMETRY: 1
      node: 20.18.1
    scripts:
      - name: Install dependencies
        script: |
          # Clean environment and install dependencies
          rm -rf node_modules
          npm cache clean --force
          npm install --legacy-peer-deps
      - name: Expo Prebuild & iOS Setup
        script: |
          # Optional: Update pods if this workflow is ever targets iOS
          # pod repo update
          npx expo prebuild --platform android
      - name: Build Android Release APK
        script: |
          npx expo export --platform android
          cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - bhaikumarark99@gmail.com
