export interface WordPair {
  wordA: string; // For Citizens
  wordB: string; // For the Spy
}

export const WORD_BANK: WordPair[] = [
  // ── Original 20 ────────────────────────────────────────────────────────────
  { wordA: 'Coffee', wordB: 'Tea' },
  { wordA: 'Instagram', wordB: 'Snapchat' },
  { wordA: 'Marvel', wordB: 'DC' },
  { wordA: 'Superman', wordB: 'Batman' },
  { wordA: 'Starbucks', wordB: 'Dunkin' },
  { wordA: 'Pizza', wordB: 'Burger' },
  { wordA: 'Apple', wordB: 'Samsung' },
  { wordA: 'Youtube', wordB: 'TikTok' },
  { wordA: 'Movie', wordB: 'Series' },
  { wordA: 'Hotel', wordB: 'Bnb' },
  { wordA: 'Soccer', wordB: 'Football' },
  { wordA: 'Harry Potter', wordB: 'Lord of the Rings' },
  { wordA: 'Winter', wordB: 'Summer' },
  { wordA: 'Rain', wordB: 'Snow' },
  { wordA: 'Cat', wordB: 'Dog' },
  { wordA: 'Forest', wordB: 'Jungle' },
  { wordA: 'Library', wordB: 'Museum' },
  { wordA: 'Mountain', wordB: 'Beach' },
  { wordA: 'Cake', wordB: 'Cookie' },
  { wordA: 'Spotify', wordB: 'Netflix' },

  // ── Tech & Social ──────────────────────────────────────────────────────────
  { wordA: 'Facebook', wordB: 'Twitter' },
  { wordA: 'Uber', wordB: 'Lyft' },
  { wordA: 'Kindle', wordB: 'iPad' },
  { wordA: 'Windows', wordB: 'MacOS' },
  { wordA: 'Discord', wordB: 'Slack' },
  { wordA: 'Visa', wordB: 'Mastercard' },
  { wordA: 'Nintendo', wordB: 'PlayStation' },
  { wordA: 'Xbox', wordB: 'PC' },
  { wordA: 'Chrome', wordB: 'Safari' },
  { wordA: 'Gmail', wordB: 'Outlook' },

  // ── Food & Drink ───────────────────────────────────────────────────────────
  { wordA: 'Coke', wordB: 'Pepsi' },
  { wordA: 'Beer', wordB: 'Wine' },
  { wordA: 'Bread', wordB: 'Rice' },
  { wordA: 'Pasta', wordB: 'Noodle' },
  { wordA: 'Steak', wordB: 'Chicken' },
  { wordA: 'Chocolate', wordB: 'Vanilla' },
  { wordA: 'Salad', wordB: 'Soup' },
  { wordA: 'Taco', wordB: 'Burrito' },
  { wordA: 'Ketchup', wordB: 'Mustard' },
  { wordA: 'Honey', wordB: 'Syrup' },
  { wordA: 'Donut', wordB: 'Bagel' },
  { wordA: 'Muffin', wordB: 'Cupcake' },
  { wordA: 'Milk', wordB: 'Juice' },
  { wordA: 'Sushi', wordB: 'Sashimi' },
  { wordA: 'Croissant', wordB: 'Toast' },
  { wordA: 'Ice Cream', wordB: 'Gelato' },
  { wordA: 'Popcorn', wordB: 'Chips' },
  { wordA: 'Water', wordB: 'Sparkling Water' },

  // ── Nature & Geography ─────────────────────────────────────────────────────
  { wordA: 'Ocean', wordB: 'Sea' },
  { wordA: 'River', wordB: 'Lake' },
  { wordA: 'Desert', wordB: 'Savanna' },
  { wordA: 'Antarctica', wordB: 'Arctic' },
  { wordA: 'Volcano', wordB: 'Earthquake' },
  { wordA: 'Cloud', wordB: 'Fog' },
  { wordA: 'Sun', wordB: 'Moon' },
  { wordA: 'Star', wordB: 'Planet' },
  { wordA: 'Island', wordB: 'Peninsula' },
  { wordA: 'Cave', wordB: 'Tunnel' },
  { wordA: 'Flower', wordB: 'Tree' },
  { wordA: 'Rose', wordB: 'Tulip' },
  { wordA: 'Lightning', wordB: 'Thunder' },
  { wordA: 'Wind', wordB: 'Storm' },

  // ── Animals ────────────────────────────────────────────────────────────────
  { wordA: 'Lion', wordB: 'Tiger' },
  { wordA: 'Wolf', wordB: 'Fox' },
  { wordA: 'Eagle', wordB: 'Hawk' },
  { wordA: 'Shark', wordB: 'Whale' },
  { wordA: 'Snake', wordB: 'Lizard' },
  { wordA: 'Hamster', wordB: 'Guinea Pig' },
  { wordA: 'Parrot', wordB: 'Canary' },
  { wordA: 'Butterfly', wordB: 'Moth' },
  { wordA: 'Spider', wordB: 'Scorpion' },
  { wordA: 'Horse', wordB: 'Donkey' },
  { wordA: 'Dolphin', wordB: 'Porpoise' },
  { wordA: 'Elephant', wordB: 'Rhino' },
  { wordA: 'Giraffe', wordB: 'Zebra' },
  { wordA: 'Owl', wordB: 'Bat' },

  // ── Entertainment & Music ──────────────────────────────────────────────────
  { wordA: 'Rock', wordB: 'Pop' },
  { wordA: 'Jazz', wordB: 'Blues' },
  { wordA: 'Hip Hop', wordB: 'R&B' },
  { wordA: 'Guitar', wordB: 'Piano' },
  { wordA: 'Drums', wordB: 'Violin' },
  { wordA: 'Broadway', wordB: 'Opera' },
  { wordA: 'Ballet', wordB: 'Contemporary' },
  { wordA: 'Chess', wordB: 'Checkers' },
  { wordA: 'Monopoly', wordB: 'Scrabble' },
  { wordA: 'Poker', wordB: 'Blackjack' },
  { wordA: 'Sudoku', wordB: 'Crossword' },
  { wordA: 'Mario', wordB: 'Sonic' },
  { wordA: 'Pokemon', wordB: 'Digimon' },

  // ── Objects & Daily Life ───────────────────────────────────────────────────
  { wordA: 'Pen', wordB: 'Pencil' },
  { wordA: 'Notebook', wordB: 'Folder' },
  { wordA: 'Laptop', wordB: 'Desktop' },
  { wordA: 'Backpack', wordB: 'Suitcase' },
  { wordA: 'Wallet', wordB: 'Purse' },
  { wordA: 'Watch', wordB: 'Clock' },
  { wordA: 'Glasses', wordB: 'Contacts' },
  { wordA: 'Mirror', wordB: 'Window' },
  { wordA: 'Pillow', wordB: 'Blanket' },
  { wordA: 'Chair', wordB: 'Stool' },
  { wordA: 'Sofa', wordB: 'Armchair' },
  { wordA: 'Towel', wordB: 'Bathrobe' },
  { wordA: 'Shampoo', wordB: 'Soap' },
  { wordA: 'Toothbrush', wordB: 'Floss' },
  { wordA: 'Umbrella', wordB: 'Raincoat' },
  { wordA: 'Bus', wordB: 'Train' },
  { wordA: 'Car', wordB: 'Taxi' },
  { wordA: 'Plane', wordB: 'Boat' },
  { wordA: 'Bicycle', wordB: 'Scooter' },

  // ── Sports & Activities ────────────────────────────────────────────────────
  { wordA: 'Tennis', wordB: 'Badminton' },
  { wordA: 'Baseball', wordB: 'Cricket' },
  { wordA: 'Basketball', wordB: 'Netball' },
  { wordA: 'Golf', wordB: 'Mini Gold' },
  { wordA: 'Bowling', wordB: 'Billiards' },
  { wordA: 'Skating', wordB: 'Skiing' },
  { wordA: 'Surfing', wordB: 'Sailing' },
  { wordA: 'Boxing', wordB: 'Wrestling' },
  { wordA: 'Gymnastics', wordB: 'Yoga' },

  // ── Places ─────────────────────────────────────────────────────────────────
  { wordA: 'School', wordB: 'University' },
  { wordA: 'Park', wordB: 'Garden' },
  { wordA: 'Beach', wordB: 'Pool' },
  { wordA: 'Office', wordB: 'Home' },
  { wordA: 'Mall', wordB: 'Market' },
  { wordA: 'Church', wordB: 'Temple' },
  { wordA: 'Airport', wordB: 'Station' },
  { wordA: 'Cinema', wordB: 'Theater' },
  { wordA: 'Restaurant', wordB: 'Cafe' },
];
